version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: aereodb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./02-data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  db_data:

